name: Build IPQ807x for AX6
on: [push]
env:
  REPO_URL: https://github.com/flyfishes/openwrt-robimarko
  REPO_BRANCH: ipq807x-5.15-pr
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: ../../kernel-5.15/config/robimarko-ax6-5.15.config
  TZ: Asia/Shanghai
  
jobs:
    build:
        name: Prepare and build IPQ807x generic images for AX6
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Initialization environment
              env:
                DEBIAN_FRONTEND: noninteractive
              run: |
                sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
                sudo -E apt-get -qq update
                sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-2004)
                sudo -E apt-get -qq autoremove --purge
                sudo -E apt-get -qq clean
                sudo timedatectl set-timezone "$TZ"
                sudo mkdir -p /workdir
                sudo chown $USER:$GROUPS /workdir
                
            - name: Clone source code
              working-directory: /workdir
              run: |
                df -hT $PWD
                git clone $REPO_URL -b $REPO_BRANCH openwrt
                ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

            - name: Update and install feeds
              run: |
                cd openwrt && ./scripts/feeds update -a
                cd openwrt && ./scripts/feeds install -a
                
              
            - name: Generate config for IPQ807x Generic
              run: |
                echo "CONFIG_TARGET_ipq807x=y" > .config
                echo "CONFIG_TARGET_ipq807x_generic=y\n" >> .config
                echo "CONFIG_TARGET_MULTI_PROFILE=y\n" >> .config
                echo "CONFIG_TARGET_ALL_PROFILES=y\n" >> .config
                echo "CONFIG_TARGET_PER_DEVICE_ROOTFS=y\n" >> .config
                echo "CONFIG_TARGET_ROOTFS_INITRAMFS=y\n" >> .config
                echo "CONFIG_TARGET_INITRAMFS_COMPRESSION_ZSTD=y\n" >> .config
                echo "CONFIG_PACKAGE_luci=y\n" >> .config
                echo "CONFIG_PACKAGE_kmod-qca-nss-dp=y\n" >> .config
                echo "CONFIG_PACKAGE_qca-ssdk-shell=y\n" >> .config
                echo "CONFIG_PACKAGE_wpad-basic-wolfssl=m\n" >> .config
                echo "CONFIG_PACKAGE_wpad-wolfssl=y\n" >> .config
                echo "copy kernel-5.15/config/robimarko-ax6-5.15.config"
                [ -e $CONFIG_FILE ] && cp $CONFIG_FILE openwrt/.config
                cd openwrt 
                cat .config
                make defconfig
            - name: Download package sources
              run: cd openwrt && make download V=s

            - name: Build tools
              run: |
                cd openwrt 
                make tools/install -j$(nproc) V=s || \
                make tools/install V=s
            - name: Build toolchain
              run: |
                cd openwrt 
                make toolchain/install -j$(nproc) V=s || \
                make toolchain/install V=s
            - name: Build target images
              run: |
                cd openwrt 
                make -j$(nproc) V=s || \
                make V=s
            - name: TAR output
              run: |
                cd openwrt
                tar -cvf ipq807xx-images.tar bin/targets/ipq807x/generic
                cp ipq807xx-images.tar ../

            - name: Upload artifacts
              uses: actions/upload-artifact@v2
              with:
                name: ipq807x-images
                path: ipq807xx-images.tar

    release:
          name: Make a release
          runs-on: ubuntu-latest
          needs: build

          steps:
            - name: Download the image artifacts
              uses: actions/download-artifact@v2
              with:
                name: ipq807x-images

            - name: Extract the image artifacts
              run: tar xf ipq807xx-images.tar

            - name: Get the current date
              run: echo "NOW=$(date +%F)" >> $GITHUB_ENV

            - name: Create a release
              uses: "lauravuo/action-automatic-releases@test-changes"
              with:
                repo_token: "${{ secrets.GITHUB_TOKEN }}"
                prerelease: true
                title: "Updated prebuilt images ${{ env.NOW }}"
                automatic_release_tag: "ipq807x-${{ env.NOW }}"
                auto_generate_release_notes: true
                files: bin/targets/ipq807x/generic/*
